default:
  image: registry.git.innokassa.ru/byurrer/docker-images/node:16.17
  tags:
    - gitlab-runner-docker

cache:
  paths:
    - node_modules/

stages:
  - test
  - build

pre-job:
  stage: .pre
  when: always
  script:
    - npm install

test:
  stage: test
  script:
    - npm run test
  coverage: '/^Lines\s*:\s*([^%]+%)/'

lint:
  stage: test
  script:
    - npm run lint

build:
  stage: build
  script:
    - npm run build
